<a href="https://colab.research.google.com/github/nidhib99/NLP/blob/master/Classwork/NLP_topic_modeling_J006.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Colab library to upload files to notebook
from google.colab import files

# Install Kaggle library
!pip install -q kaggle

In [0]:
# Upload kaggle API key file
uploaded = files.upload()

Saving kaggle.json to kaggle.json


In [0]:
!cp kaggle.json ~/.kaggle/kaggle.json
#!mkdir ~/.kaggle
#!cp /content/.kaggle/kaggle.json ~/.kaggle/kaggle.json

In [0]:
!kaggle datasets download -d hj5992/nlp-topic-modelling

 99% 113M/115M [00:05<00:00, 20.6MB/s] 
100% 115M/115M [00:05<00:00, 22.8MB/s]


In [0]:
# Import pandas if you already haven't
import pandas as pd

# Import the test and train datasets into pandas dataframe
df = pd.read_csv('nlp-topic-modelling.zip', compression='zip', header=0, sep=',', quotechar='"')

In [0]:
df

Id  ...                                               Text
0            1  ...  I have bought several of the Vitality canned d...
1            2  ...  Product arrived labeled as Jumbo Salted Peanut...
2            3  ...  This is a confection that has been around a fe...
3            4  ...  If you are looking for the secret ingredient i...
4            5  ...  Great taffy at a great price.  There was a wid...
...        ...  ...                                                ...
568449  568450  ...  Great for sesame chicken..this is a good if no...
568450  568451  ...  I'm disappointed with the flavor. The chocolat...
568451  568452  ...  These stars are small, so you can give 10-15 o...
568452  568453  ...  These are the BEST treats for training and rew...
568453  568454  ...  I am very satisfied ,product is as advertised,...

[568454 rows x 10 columns]

In [0]:
import re
import nltk
import itertools
import pandas as pd
from gensim import models
from nltk import word_tokenize
from nltk.corpus import stopwords
from gensim.models import Word2Vec
from itertools import combinations
from string import digits,punctuation 
from nltk.tokenize import word_tokenize
from gensim.test.utils import get_tmpfile, common_texts
nltk.download('punkt')
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('stopwords') 
nltk.download('averaged_perceptron_tagger')

remove_digits = str.maketrans('', '', digits)
stop_words = set(stopwords.words('english'))

def tokens(str):
  str = str.lower()
  str = str.translate(remove_digits)
  str = re.sub(r'[^\w\s]',' ',str)
  token = word_tokenize(str)
  words = [word for word in token if word not in stop_words and word not in punctuation]
  return words

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


In [0]:
df2 = df[['Text']]

In [0]:
df2 = df2.head(10000)

In [0]:
df2['Text1'] = df2['Text'].apply(tokens)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [0]:
from sklearn.feature_extraction.text import TfidfVectorizer
def dummy_fun(doc):
    return doc
vectorizer = TfidfVectorizer(analyzer='word',tokenizer=dummy_fun,preprocessor=dummy_fun,token_pattern=None)
vectors = vectorizer.fit_transform(df2['Text1'])
feature_names = vectorizer.get_feature_names()
dense = vectors.todense()
denselist = dense.tolist()
df3 = pd.DataFrame(denselist, columns=feature_names)

In [0]:
df3

____________________________________________________________________________________________________________________________  ...   ît
0                                                   0.0                                                                             ...  0.0
1                                                   0.0                                                                             ...  0.0
2                                                   0.0                                                                             ...  0.0
3                                                   0.0                                                                             ...  0.0
4                                                   0.0                                                                             ...  0.0
...                                                 ...                                                                             ...  ...
9995                                                0.0                                                                             ...  0.0
9996                                                0.0                                                                             ...  0.0
9997                                                0.0                                                                             ...  0.0
9998                                                0.0                                                                             ...  0.0
9999                                                0.0                                                                             ...  0.0

[10000 rows x 18099 columns]

In [0]:
df3 = df3.drop(["____________________________________________________________________________________________________________________________"], 1)

In [0]:
df3

_effect_  _i_  _really_  _still_  _totally  ...  zuppa    º    ¼    ½   ît
0          0.0  0.0       0.0      0.0       0.0  ...    0.0  0.0  0.0  0.0  0.0
1          0.0  0.0       0.0      0.0       0.0  ...    0.0  0.0  0.0  0.0  0.0
2          0.0  0.0       0.0      0.0       0.0  ...    0.0  0.0  0.0  0.0  0.0
3          0.0  0.0       0.0      0.0       0.0  ...    0.0  0.0  0.0  0.0  0.0
4          0.0  0.0       0.0      0.0       0.0  ...    0.0  0.0  0.0  0.0  0.0
...        ...  ...       ...      ...       ...  ...    ...  ...  ...  ...  ...
9995       0.0  0.0       0.0      0.0       0.0  ...    0.0  0.0  0.0  0.0  0.0
9996       0.0  0.0       0.0      0.0       0.0  ...    0.0  0.0  0.0  0.0  0.0
9997       0.0  0.0       0.0      0.0       0.0  ...    0.0  0.0  0.0  0.0  0.0
9998       0.0  0.0       0.0      0.0       0.0  ...    0.0  0.0  0.0  0.0  0.0
9999       0.0  0.0       0.0      0.0       0.0  ...    0.0  0.0  0.0  0.0  0.0

[10000 rows x 18098 columns]

In [0]:
from sklearn.decomposition import NMF

In [0]:
model = NMF(n_components=5, init='nndsvd', random_state=42, alpha = 0.1, l1_ratio = 0.5)

In [0]:
W = model.fit_transform(df3)
H = model.components_

In [0]:
print(W)

[[2.90417840e-02 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [8.24159353e-03 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [5.10523295e-03 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 ...
 [1.89638619e-02 0.00000000e+00 5.31859278e-05 0.00000000e+00
  0.00000000e+00]
 [1.17734132e-02 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [2.30465428e-02 0.00000000e+00 4.55296170e-03 0.00000000e+00
  0.00000000e+00]]


In [0]:
print(H)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [0]:
w = pd.DataFrame(W)
h = pd.DataFrame(H)

In [0]:
import numpy as np
def display_topics(H, W, feature_names, documents, no_top_words, no_top_documents):
    for topic_idx, topic in enumerate(H):
        print("Topic %d:" % (topic_idx))
        print(" ".join([feature_names[i]
        for i in topic.argsort()[:-no_top_words - 1:-1]]))
        top_doc_indices = np.argsort( W[:,topic_idx] )[::-1][0:no_top_documents]
        for doc_index in top_doc_indices:
            print(documents[doc_index])

In [0]:
display_topics(H,W,list(df3),df["Text"],1,5)

Topic 0:
good
I did not purchase this product off of Amazon. I purchased the 12 oz. bottle at a local store, and I must say it's one of the most addicting sauces I have ever had! I'm a pretty picky eater, and a vegetarian at that, so sauces play a key role in making an average meal a great one. This sauce is ALMOST perfect. It's very sweet, and has a strong garlic taste at first. It isn't as thick as the Red Hot brand, which I didn't like much at all (thick, not as flavorful, way too chunky). This sauce would be appropriate for children who like a little kick for their chicken nuggets and what not. My son loves spicy food just like his mommy. Another plus is there are only 70 calories in 2 tablespoons, and that much sauce goes a long way. 1 gram of fiber, too! The only thing I have a hard time with, and this is just a personal issue, is the texture of the red chilli. They tastes great, but they have a very thin, clear "skin" that has this horrible crunchy texture on some of the pieces.

In [0]:
from sklearn.decomposition import LatentDirichletAllocation
lda = LatentDirichletAllocation(n_components = 10, random_state=0)
lda.fit(df3)

LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
                          evaluate_every=-1, learning_decay=0.7,
                          learning_method='batch', learning_offset=10.0,
                          max_doc_update_iter=100, max_iter=10,
                          mean_change_tol=0.001, n_components=10, n_jobs=None,
                          perp_tol=0.1, random_state=0, topic_word_prior=None,
                          total_samples=1000000.0, verbose=0)

In [0]:
def print_top_words(model, feature_names, n_top_words):
    for topic_idx, topic in enumerate(model.components_):
        message = "Topic #%d: " % topic_idx
        message += " ".join([feature_names[i]
                             for i in topic.argsort()[:-n_top_words - 1:-1]])
        print(message)
    print()
print_top_words(lda, list(df3), 10)

Topic #0: win spectacular butterfinger coriander toffee workers cashews baste brazil walk
Topic #1: mix pancakes gluten free bisquick waffles pancake biscuits gf cake
Topic #2: coffee tea br cup like taste chocolate flavor good one
Topic #3: sumatran nantucket overtone raya mountain dulce terribly de verona leche
Topic #4: br food chips dog great good love like eat product
Topic #5: watchers span kellogg husbands points situation labs guessed sooner definatly
Topic #6: coffee cup k cups flavor wolfgang great good puck product
Topic #7: oreo automatically slimy cakesters rocks novelty hassle grand corner merchandise
Topic #8: fondant fondarific dd stuffer pots dying bordering ty crystals minced
Topic #9: br like taste good great sugar flavor juice product orange

